#include "vcs.h"
#include "vcs_colors.h"

unsigned char X, Y;

#define BLANK 40
#define KERNAL 192
#define OVERSCAN 30

// Helloworld 48 pixels wide generated by tools2600/text2rom2600
aligned(256) const char line0[42] = {
	0x50, 0x50, 0x52, 0x75, 0x57, 0x54, 0x53, 
	0x66, 0x22, 0x22, 0x22, 0x22, 0x22, 0x77, 
	0x00, 0x00, 0x20, 0x50, 0x50, 0x50, 0x20, 
	0x50, 0x50, 0x52, 0x75, 0x75, 0x75, 0x52, 
	0x06, 0x02, 0x62, 0x52, 0x42, 0x42, 0x47, 
	0x12, 0x12, 0x32, 0x52, 0x52, 0x50, 0x32};

void init()
{
    *COLUBK = VCS_BLACK;
    *COLUP0 = VCS_WHITE;
    *COLUP1 = VCS_WHITE;
}

void main()
{
    init();

    while(1) {
        *VBLANK = 2; // Disable VBLANK
        *VSYNC = 2; // Set VSYNC
        strobe(WSYNC); // Hold it for 3 scanlines
        strobe(WSYNC);
        strobe(WSYNC);
        *VSYNC = 0; // Turn VSYNC Off
        
        // Blank
        *TIM64T = ((BLANK - 3) * 76) / 64 + 1;
        // Do some logic here

        Y = KERNAL; // Initialize line counter

        // Do some extra logic
        
        while (*INTIM);
        
        // Image drawing
        strobe(WSYNC);
        *VBLANK = 0;
        Y--;
        do {
            strobe(WSYNC);
            Y--;
        } while (Y);
        // Last line is out of loop and is generally simpler
        strobe(WSYNC);
        
        strobe(WSYNC);
        // Overscan
        *VBLANK = 2; // Enable VBLANK
        *TIM64T = (OVERSCAN * 76) / 64;
        // Do some logic here
        while (*INTIM);
    }
}
